In [1]:
import modules.capiq as capiq

In [2]:
# Component type table
capiq.ciqtranscriptcomponenttype()

Loading library list...
Done
WRDS connection established.

   transcriptcomponenttypeid           transcriptcomponenttypename
0                          1         Presentation Operator Message
1                          2                      Presenter Speech
2                          3                              Question
3                          4                                Answer
4                          5                  Presentation Section
5                          6           Question And Answer Section
6                          7  Question and Answer Operator Message
7                          8   Unknown Question and Answer Message

In [3]:
# Download transcripts
transcript_df, person_df = capiq.dl_transcripts([9063, 15056])

In [4]:
transcript_df

,transcriptcomponentid,transcriptid,componentorder,transcriptcomponenttypeid,transcriptpersonid,componenttext
118,688120,9063,1,1,1,"Good morning. My name is Andrea, and I will be..."
1,688121,9063,2,2,50718,"Thank you for joining us today, and welcome to..."
46,688122,9063,3,2,50733,Good morning. This is Joe Shoen. I am speaking...
85,688123,9063,4,2,50718,"Andrea, we're ready for question-and-answers.\n"
120,688124,9063,5,2,50733,"Andrea, this is Joe at U-Haul. We would like t..."
...,...,...,...,...,...,...
172,1081138,15056,97,4,57496,"Under leasing, it is a very interesting becaus..."
202,1081139,15056,98,3,51252,Okay. Gary thanks.\n
227,1081140,15056,99,7,1,"Mr. Shoen, if you would like to make any closi..."
252,1081141,15056,100,4,74946,"Well, thank you all very much for your support..."
173,1081142,15056,101,7,1,This concludes today’s conference call. You ma...

In [5]:
person_df

,transcriptcomponentid,transcriptid,transcriptpersonname,companyofperson,speakertypename
0,688171.0,9063.0,Ross Haberman,None,Analysts
1,688234.0,9063.0,Simon Willis,None,Analysts
2,688132.0,9063.0,Ian Gilson,None,Analysts
3,688170.0,9063.0,Rocky Wardrip,None,Executives
4,688120.0,9063.0,Operator,None,Operator
...,...,...,...,...,...
248,1081138.0,15056.0,Gary Horton,None,Executives
249,1081139.0,15056.0,Ian Gilson,Zacks Investments,Analysts
250,1081140.0,15056.0,Operator,None,Operator
251,1081141.0,15056.0,Edward Shoen,None,Executives
252,1081142.0,15056.0,Operator,None,Operator

In [6]:
formatted_transcripts = capiq.format_transcript(transcript_df, person_df)
formatted_transcripts

{np.int64(9063): '[\n {\n  "transcriptcomponenttypename":"Presentation Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Good morning. My name is Andrea, and I will be your conference operator today. At this time, I would like to welcome everyone to the AMERCO third quarter fiscal 2008 investor conference call. (Operator Instructions)\\nThank you. Ms. Flachman, you may begin your conference.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Thank you for joining us today, and welcome to the AMERCO third quarter fiscal 2008 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995. Certain factors could cause actual results to differ materially from those projected. For a brief discussion of the risks and uncertainties that may affect AMERCO\'s business and future operating results, please refer to Form 10-Q for the quarter ended December 31, 2007, which is on file with the Securities and Exchange Commission.\\nParticipating in the call today will be Joe Shoen, AMERCO\'s Chairman. I will now turn the call over to Mr. Shoen.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning. This is Joe Shoen. I am speaking you to you from Phoenix, Arizona. Rocky Wardrip, our Assistant treasurer and Jason Berg our Chief Accounting Officer are on the call with me today and they will both be available for questions.\\nU-Haul continued to experience a tough revenue and transaction environment in the just finished third quarter. At the same time, we continued to reap the expense line benefits of the heavy investments we\'ve made in truck replacements over the past 30 months. The primary cost reduction was in repair and maintenance expense on trucks that are no longer in our rental fleet, another word is retired vehicles.\\nWe will continue to aggressively bring in new truck replacements through at least the next two quarters. Our new rental truck weight making system we introduced late last spring has starting to show some results. It allows us to manage with more precision in many small markets we serve and U-Haul\'s distinguished from it\'s compared in that we are in many small markets.\\nWe continue to show rate leadership where we can do so without adversely effecting market share. I intend for us to continue to do this, however, overall rates remain depressed. As I mentioned repair and maintenance was a bright spot in the quarter and it was largely result of decisions made a year or more ago. At the point of sales, my current efforts are focused on improving the rental experience of our exiting customer base. Working on the fundamentals of blocking and tackling in our business will clearly deliver improved results over the long-term.\\nI\'m watching the macro environment in terms of fuel issues and sustainability issues. I don\'t believe they are presently impacting on results but I think they are capable of doing so. My intent is to have U-Haul positioned a little bit ahead of problem should they arise.\\nOverall U-Haul equipment rentals will likely be very tight in the fourth quarter. As I have indicated before, U-Haul is vulnerable to bad winter weather as this late in the year of loss of gross revenue flows disproportionately to the bottomline. On the other hand, our U-Haul self-storage product did not have this same issue and is more predictable. On the insurance company front, both the insurance companies continue to deliver results at planned levels. You should expect them to continue to do so over the near term.\\nWe\'ll now go to the question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, we\'re ready for question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, this is Joe at U-Haul. We would like to go to question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"At this time, sir, your first question comes from Ian Gilson.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Well, how are you, Ian?\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good results. Very good results. I do have a question regarding the operating segment\'s results and I know that SAC Holding revenue dropped from $10.8 million to $3.55 million and the earnings from operations dropped to $3.01 to $0.85 million. Did they sell properties or what happened here?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Hi, Ian. This is Jason. During the quarter SAC Holding II was deconsolidated from our financial statements. SAC Holding II\'s parent company, Blackwater, made a contribution to SAC Holding II, that triggered a reevaluation of its consolidated status with us. We made that evaluation and based upon our accounting analysis of the facts and circumstances, they were deconsolidated effective October 31st. So, the results shown in the financial statements you\'re looking for a fiscal 2008, the third quarter includes only one month of activity for SAC Holding II. In future periods, we will not be consolidating any new activity from SAC Holding II.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I would add to that that I consider this a blessing. The last four years we\'ve been stuck in an accounting convention that caused us to consolidate certain of the income and expenses of that company, although that didn\'t reflect any of the actual economic benefit either way. Going ahead, you\'ll see the SAC relationship in management fee income and interest income and that will be more predictable, and it also indicates true economic affect.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. So there is an impact on the overall income statement, but it\'s like a minority ownership.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, not exactly. We won\'t be showing any of their future income. Now we still have to consolidate their activity through October 31st, so you are going to see those numbers remain in the financial statements as long as those historical periods are shown, but going forward any new activity will not be consolidated.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"You have no financial interest in SAC II?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No. We no longer consolidate SAC II. But we still have junior notes with them, interest income and we also manage their storage properties for them. We will receive management fees from them, which will show up in the U-Haul financial statements as management fee income.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Which is precisely what the economic relationship has been, but the accounting presentation has been subject to certain accounting conventions that aren\'t always get on with the economic relations should be. And now these two are going to be mere each other more closely. Including them in our gross revenue is confusing, but including them in our interest income which we do get actual interest income managed with fee income and of course, to the extent they are U-Haul dealers or they do U-Haul revenue, of course, we see all that revenue. So there is still a lot of flows, but the flows are presented on an income statement basis, which is really where the economic interest is.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Since you do get the benefit of the U-Haul dealer on the storage side, is SAC II growing, stable, declining? Can you give us an idea of what that U-Haul revenue streamline look like?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"The U-Haul revenue stream that we receive from the management fee...\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, no he means the truck\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Yeah. The truck rental from the sites that are in the SAC II and other SAC properties.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They very much mere the entire company. So I can\'t give you, I don\'t have it in my command their actual quarter results. They are going to be very much -- mirror the whole company. So in other words they were flat for the quarter or maybe up a tiny of a percent or something. There is no prospect of them diminishing, Ian, but I would expect them to grow at or below the companies overall because SAC is not adding the locations in the -- going ahead as we add a location. The intent is to add it at the U-Haul level and not at the SAC level. So you would see hopefully more growth at the U-Haul level.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Great. Thanks very much.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Your next question comes from the line of Jim Barrett.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning, everyone.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, Jim.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Joe, you talk about that in a couple of quarters as you see the above average investment in trucks are coming down, can you give us any sense as to what the - first of all, what the might represent?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"If I said that, I misspoke a little bit. For the next two quarters, I expect to continue to be aggressive which is above what you\'ve seen going on, okay. I think we\'re -- Jason you might correct me, we have something like 7,000 to 10,000 trucks we\'re committed to right now and that\'s a strong replacement, I am hedging my bid as to what all do mid-summer, another words going into the second quarter of the New Year, which should be more than 180 days from now because we\'re kind of getting somewhere is near the tipping point where we\'ve done enough replacement and if were not going to see increased revenue which we haven\'t seen as you know, Jim, over the last 16 months -- if we\'re not going to see increased revenue than we shouldn\'t increase the truck fleet.\\nI wish I could, it may sound very crude to you that this could be a 5,000 or 7,000 truck window but that\'s really about as precise as it can be. Somewhere in there, where I think we\'ve replaced trucks that we needed to do aggressively and we would go into a more normal cycle, which very likely would be this August or September. And that would be a reduction, a guess at that, Jim would be to take and put it at 10,000 trucks annually.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"On a going forward basis is that sort of beyond this summer that would be sort of a broad run rate?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think that would be with the exception that if we saw some big market opportunity but there has been no big market opportunity we\'ve identified over the last 16 months. So I mean, I am the eternal optimist, I am always looking forward, but we\'re not going to spend money based on optimism. We\'re going to have a definite plan and see something that we can pro forma out over a period of years.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"If it comes to that, Joe, doesn\'t that mean your capital expenditures do come down markedly?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They come down -- I would defer to Rocky as to exactly how that trickles through the whole financial statement because it\'s never is direct but ordinarily my experience is when those come down you pick up a little bit of an income. Rocky, you might comment on that.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Yeah. And my guess, Jim, and depending on the mix what you\'re putting in, is that would probably bring annual truck expenditures down on a net basis just somewhere between $200 million and $225 million.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"And then I would add to that the -- whatever investments you\'re making in self-storage to get an idea what your gross CapEx is?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s correct.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Joe, if the firm does\\u2026.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"(Operator Instructions) Your next question comes from the line of Ross Haberman.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"How are you?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"I think you might have cut Barrett off, but I am sure he will come back on. Joe, a follow up to his question, what is the cap -- have you said what the capital expenditures are going to be calendar \'08 in total?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, we haven\'t. We actually do that calculation based on the fiscal year which is, as you know, March 31 anniversary. So, no, we haven\'t. Rocky may have, of course, he\'s constantly projecting it on a rolling basis, but I don\'t know Rocky.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have you spend to date, Rocky, if I may ask?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I beg your pardon.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have we spent for the nine months, I guess for CapEx?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jason, do you have that number handy. I don\'t have it on my fingertips.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Including everything we\'ve for the nine months it was $420 million of which truck purchases are the largest portion of that that also includes all other CapEx too which would include storage.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Is that a net or is that a gross number?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s a gross number.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Okay. Because this is very confusing and\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "tr

In [7]:
formatted_transcripts = capiq.get_transcripts([9063, 15056])
formatted_transcripts

{np.int64(9063): '[\n {\n  "transcriptcomponenttypename":"Presentation Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Good morning. My name is Andrea, and I will be your conference operator today. At this time, I would like to welcome everyone to the AMERCO third quarter fiscal 2008 investor conference call. (Operator Instructions)\\nThank you. Ms. Flachman, you may begin your conference.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Thank you for joining us today, and welcome to the AMERCO third quarter fiscal 2008 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995. Certain factors could cause actual results to differ materially from those projected. For a brief discussion of the risks and uncertainties that may affect AMERCO\'s business and future operating results, please refer to Form 10-Q for the quarter ended December 31, 2007, which is on file with the Securities and Exchange Commission.\\nParticipating in the call today will be Joe Shoen, AMERCO\'s Chairman. I will now turn the call over to Mr. Shoen.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning. This is Joe Shoen. I am speaking you to you from Phoenix, Arizona. Rocky Wardrip, our Assistant treasurer and Jason Berg our Chief Accounting Officer are on the call with me today and they will both be available for questions.\\nU-Haul continued to experience a tough revenue and transaction environment in the just finished third quarter. At the same time, we continued to reap the expense line benefits of the heavy investments we\'ve made in truck replacements over the past 30 months. The primary cost reduction was in repair and maintenance expense on trucks that are no longer in our rental fleet, another word is retired vehicles.\\nWe will continue to aggressively bring in new truck replacements through at least the next two quarters. Our new rental truck weight making system we introduced late last spring has starting to show some results. It allows us to manage with more precision in many small markets we serve and U-Haul\'s distinguished from it\'s compared in that we are in many small markets.\\nWe continue to show rate leadership where we can do so without adversely effecting market share. I intend for us to continue to do this, however, overall rates remain depressed. As I mentioned repair and maintenance was a bright spot in the quarter and it was largely result of decisions made a year or more ago. At the point of sales, my current efforts are focused on improving the rental experience of our exiting customer base. Working on the fundamentals of blocking and tackling in our business will clearly deliver improved results over the long-term.\\nI\'m watching the macro environment in terms of fuel issues and sustainability issues. I don\'t believe they are presently impacting on results but I think they are capable of doing so. My intent is to have U-Haul positioned a little bit ahead of problem should they arise.\\nOverall U-Haul equipment rentals will likely be very tight in the fourth quarter. As I have indicated before, U-Haul is vulnerable to bad winter weather as this late in the year of loss of gross revenue flows disproportionately to the bottomline. On the other hand, our U-Haul self-storage product did not have this same issue and is more predictable. On the insurance company front, both the insurance companies continue to deliver results at planned levels. You should expect them to continue to do so over the near term.\\nWe\'ll now go to the question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, we\'re ready for question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, this is Joe at U-Haul. We would like to go to question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"At this time, sir, your first question comes from Ian Gilson.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Well, how are you, Ian?\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good results. Very good results. I do have a question regarding the operating segment\'s results and I know that SAC Holding revenue dropped from $10.8 million to $3.55 million and the earnings from operations dropped to $3.01 to $0.85 million. Did they sell properties or what happened here?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Hi, Ian. This is Jason. During the quarter SAC Holding II was deconsolidated from our financial statements. SAC Holding II\'s parent company, Blackwater, made a contribution to SAC Holding II, that triggered a reevaluation of its consolidated status with us. We made that evaluation and based upon our accounting analysis of the facts and circumstances, they were deconsolidated effective October 31st. So, the results shown in the financial statements you\'re looking for a fiscal 2008, the third quarter includes only one month of activity for SAC Holding II. In future periods, we will not be consolidating any new activity from SAC Holding II.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I would add to that that I consider this a blessing. The last four years we\'ve been stuck in an accounting convention that caused us to consolidate certain of the income and expenses of that company, although that didn\'t reflect any of the actual economic benefit either way. Going ahead, you\'ll see the SAC relationship in management fee income and interest income and that will be more predictable, and it also indicates true economic affect.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. So there is an impact on the overall income statement, but it\'s like a minority ownership.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, not exactly. We won\'t be showing any of their future income. Now we still have to consolidate their activity through October 31st, so you are going to see those numbers remain in the financial statements as long as those historical periods are shown, but going forward any new activity will not be consolidated.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"You have no financial interest in SAC II?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No. We no longer consolidate SAC II. But we still have junior notes with them, interest income and we also manage their storage properties for them. We will receive management fees from them, which will show up in the U-Haul financial statements as management fee income.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Which is precisely what the economic relationship has been, but the accounting presentation has been subject to certain accounting conventions that aren\'t always get on with the economic relations should be. And now these two are going to be mere each other more closely. Including them in our gross revenue is confusing, but including them in our interest income which we do get actual interest income managed with fee income and of course, to the extent they are U-Haul dealers or they do U-Haul revenue, of course, we see all that revenue. So there is still a lot of flows, but the flows are presented on an income statement basis, which is really where the economic interest is.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Since you do get the benefit of the U-Haul dealer on the storage side, is SAC II growing, stable, declining? Can you give us an idea of what that U-Haul revenue streamline look like?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"The U-Haul revenue stream that we receive from the management fee...\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, no he means the truck\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Yeah. The truck rental from the sites that are in the SAC II and other SAC properties.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They very much mere the entire company. So I can\'t give you, I don\'t have it in my command their actual quarter results. They are going to be very much -- mirror the whole company. So in other words they were flat for the quarter or maybe up a tiny of a percent or something. There is no prospect of them diminishing, Ian, but I would expect them to grow at or below the companies overall because SAC is not adding the locations in the -- going ahead as we add a location. The intent is to add it at the U-Haul level and not at the SAC level. So you would see hopefully more growth at the U-Haul level.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Great. Thanks very much.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Your next question comes from the line of Jim Barrett.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning, everyone.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, Jim.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Joe, you talk about that in a couple of quarters as you see the above average investment in trucks are coming down, can you give us any sense as to what the - first of all, what the might represent?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"If I said that, I misspoke a little bit. For the next two quarters, I expect to continue to be aggressive which is above what you\'ve seen going on, okay. I think we\'re -- Jason you might correct me, we have something like 7,000 to 10,000 trucks we\'re committed to right now and that\'s a strong replacement, I am hedging my bid as to what all do mid-summer, another words going into the second quarter of the New Year, which should be more than 180 days from now because we\'re kind of getting somewhere is near the tipping point where we\'ve done enough replacement and if were not going to see increased revenue which we haven\'t seen as you know, Jim, over the last 16 months -- if we\'re not going to see increased revenue than we shouldn\'t increase the truck fleet.\\nI wish I could, it may sound very crude to you that this could be a 5,000 or 7,000 truck window but that\'s really about as precise as it can be. Somewhere in there, where I think we\'ve replaced trucks that we needed to do aggressively and we would go into a more normal cycle, which very likely would be this August or September. And that would be a reduction, a guess at that, Jim would be to take and put it at 10,000 trucks annually.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"On a going forward basis is that sort of beyond this summer that would be sort of a broad run rate?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think that would be with the exception that if we saw some big market opportunity but there has been no big market opportunity we\'ve identified over the last 16 months. So I mean, I am the eternal optimist, I am always looking forward, but we\'re not going to spend money based on optimism. We\'re going to have a definite plan and see something that we can pro forma out over a period of years.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"If it comes to that, Joe, doesn\'t that mean your capital expenditures do come down markedly?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They come down -- I would defer to Rocky as to exactly how that trickles through the whole financial statement because it\'s never is direct but ordinarily my experience is when those come down you pick up a little bit of an income. Rocky, you might comment on that.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Yeah. And my guess, Jim, and depending on the mix what you\'re putting in, is that would probably bring annual truck expenditures down on a net basis just somewhere between $200 million and $225 million.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"And then I would add to that the -- whatever investments you\'re making in self-storage to get an idea what your gross CapEx is?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s correct.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Joe, if the firm does\\u2026.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"(Operator Instructions) Your next question comes from the line of Ross Haberman.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"How are you?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"I think you might have cut Barrett off, but I am sure he will come back on. Joe, a follow up to his question, what is the cap -- have you said what the capital expenditures are going to be calendar \'08 in total?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, we haven\'t. We actually do that calculation based on the fiscal year which is, as you know, March 31 anniversary. So, no, we haven\'t. Rocky may have, of course, he\'s constantly projecting it on a rolling basis, but I don\'t know Rocky.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have you spend to date, Rocky, if I may ask?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I beg your pardon.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have we spent for the nine months, I guess for CapEx?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jason, do you have that number handy. I don\'t have it on my fingertips.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Including everything we\'ve for the nine months it was $420 million of which truck purchases are the largest portion of that that also includes all other CapEx too which would include storage.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Is that a net or is that a gross number?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s a gross number.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Okay. Because this is very confusing and\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "tr

In [8]:
print(formatted_transcripts[9063])

[
 {
  "transcriptcomponenttypename":"Presentation Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Good morning. My name is Andrea, and I will be your conference operator today. At this time, I would like to welcome everyone to the AMERCO third quarter fiscal 2008 investor conference call. (Operator Instructions)\nThank you. Ms. Flachman, you may begin your conference.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Jennifer Flachman",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Thank you for joining us today, and welcome to the AMERCO third quarter fiscal 2008 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995. Certain factors could cause actual results to differ materially from those projected. For a brief discussion of the risks and uncertainties that may affect AMERCO's business and future operating results, please refer to Form 10-Q for the quarter ended December 31, 2007, which is on file with the Securities and Exchange Commission.\nParticipating in the call today will be Joe Shoen, AMERCO's Chairman. I will now turn the call over to Mr. Shoen.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning. This is Joe Shoen. I am speaking you to you from Phoenix, Arizona. Rocky Wardrip, our Assistant treasurer and Jason Berg our Chief Accounting Officer are on the call with me today and they will both be available for questions.\nU-Haul continued to experience a tough revenue and transaction environment in the just finished third quarter. At the same time, we continued to reap the expense line benefits of the heavy investments we've made in truck replacements over the past 30 months. The primary cost reduction was in repair and maintenance expense on trucks that are no longer in our rental fleet, another word is retired vehicles.\nWe will continue to aggressively bring in new truck replacements through at least the next two quarters. Our new rental truck weight making system we introduced late last spring has starting to show some results. It allows us to manage with more precision in many small markets we serve and U-Haul's distinguished from it's compared in that we are in many small markets.\nWe continue to show rate leadership where we can do so without adversely effecting market share. I intend for us to continue to do this, however, overall rates remain depressed. As I mentioned repair and maintenance was a bright spot in the quarter and it was largely result of decisions made a year or more ago. At the point of sales, my current efforts are focused on improving the rental experience of our exiting customer base. Working on the fundamentals of blocking and tackling in our business will clearly deliver improved results over the long-term.\nI'm watching the macro environment in terms of fuel issues and sustainability issues. I don't believe they are presently impacting on results but I think they are capable of doing so. My intent is to have U-Haul positioned a little bit ahead of problem should they arise.\nOverall U-Haul equipment rentals will likely be very tight in the fourth quarter. As I have indicated before, U-Haul is vulnerable to bad winter weather as this late in the year of loss of gross revenue flows disproportionately to the bottomline. On the other hand, our U-Haul self-storage product did not have this same issue and is more predictable. On the insurance company front, both the insurance companies continue to deliver results at planned levels. You should expect them to continue to do so over the near term.\nWe'll now go to the question-and-answers.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Jennifer Flachman",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Andrea, we're ready for question-and-answers.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Andrea, this is Joe at U-Haul. We would like to go to question-and-answers.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"At this time, sir, your first question comes from Ian Gilson.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Well, how are you, Ian?\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Good results. Very good results. I do have a question regarding the operating segment's results and I know that SAC Holding revenue dropped from $10.8 million to $3.55 million and the earnings from operations dropped to $3.01 to $0.85 million. Did they sell properties or what happened here?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Hi, Ian. This is Jason. During the quarter SAC Holding II was deconsolidated from our financial statements. SAC Holding II's parent company, Blackwater, made a contribution to SAC Holding II, that triggered a reevaluation of its consolidated status with us. We made that evaluation and based upon our accounting analysis of the facts and circumstances, they were deconsolidated effective October 31st. So, the results shown in the financial statements you're looking for a fiscal 2008, the third quarter includes only one month of activity for SAC Holding II. In future periods, we will not be consolidating any new activity from SAC Holding II.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I would add to that that I consider this a blessing. The last four years we've been stuck in an accounting convention that caused us to consolidate certain of the income and expenses of that company, although that didn't reflect any of the actual economic benefit either way. Going ahead, you'll see the SAC relationship in management fee income and interest income and that will be more predictable, and it also indicates true economic affect.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Okay. So there is an impact on the overall income statement, but it's like a minority ownership.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"No, not exactly. We won't be showing any of their future income. Now we still have to consolidate their activity through October 31st, so you are going to see those numbers remain in the financial statements as long as those historical periods are shown, but going forward any new activity will not be consolidated.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"You have no financial interest in SAC II?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"No. We no longer consolidate SAC II. But we still have junior notes with them, interest income and we also manage their storage properties for them. We will receive management fees from them, which will show up in the U-Haul financial statements as management fee income.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Which is precisely what the economic relationship has been, but the accounting presentation has been subject to certain accounting conventions that aren't always get on with the economic relations should be. And now these two are going to be mere each other more closely. Including them in our gross revenue is confusing, but including them in our interest income which we do get actual interest income managed with fee income and of course, to the extent they are U-Haul dealers or they do U-Haul revenue, of course, we see all that revenue. So there is still a lot of flows, but the flows are presented on an income statement basis, which is really where the economic interest is.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Okay. Since you do get the benefit of the U-Haul dealer on the storage side, is SAC II growing, stable, declining? Can you give us an idea of what that U-Haul revenue streamline look like?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"The U-Haul revenue stream that we receive from the management fee...\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"No, no he means the truck\u2026\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Yeah. The truck rental from the sites that are in the SAC II and other SAC properties.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"They very much mere the entire company. So I can't give you, I don't have it in my command their actual quarter results. They are going to be very much -- mirror the whole company. So in other words they were flat for the quarter or maybe up a tiny of a percent or something. There is no prospect of them diminishing, Ian, but I would expect them to grow at or below the companies overall because SAC is not adding the locations in the -- going ahead as we add a location. The intent is to add it at the U-Haul level and not at the SAC level. So you would see hopefully more growth at the U-Haul level.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Okay. Great. Thanks very much.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Your next question comes from the line of Jim Barrett.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Good morning, everyone.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning, Jim.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Joe, you talk about that in a couple of quarters as you see the above average investment in trucks are coming down, can you give us any sense as to what the - first of all, what the might represent?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"If I said that, I misspoke a little bit. For the next two quarters, I expect to continue to be aggressive which is above what you've seen going on, okay. I think we're -- Jason you might correct me, we have something like 7,000 to 10,000 trucks we're committed to right now and that's a strong replacement, I am hedging my bid as to what all do mid-summer, another words going into the second quarter of the New Year, which should be more than 180 days from now because we're kind of getting somewhere is near the tipping point where we've done enough replacement and if were not going to see increased revenue which we haven't seen as you know, Jim, over the last 16 months -- if we're not going to see increased revenue than we shouldn't increase the truck fleet.\nI wish I could, it may sound very crude to you that this could be a 5,000 or 7,000 truck window but that's really about as precise as it can be. Somewhere in there, where I think we've replaced trucks that we needed to do aggressively and we would go into a more normal cycle, which very likely would be this August or September. And that would be a reduction, a guess at that, Jim would be to take and put it at 10,000 trucks annually.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"On a going forward basis is that sort of beyond this summer that would be sort of a broad run rate?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I think that would be with the exception that if we saw some big market opportunity but there has been no big market opportunity we've identified over the last 16 months. So I mean, I am the eternal optimist, I am always looking forward, but we're not going to spend money based on optimism. We're going to have a definite plan and see something that we can pro forma out over a period of years.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"If it comes to that, Joe, doesn't that mean your capital expenditures do come down markedly?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"They come down -- I would defer to Rocky as to exactly how that trickles through the whole financial statement because it's never is direct but ordinarily my experience is when those come down you pick up a little bit of an income. Rocky, you might comment on that.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Rocky Wardrip",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Yeah. And my guess, Jim, and depending on the mix what you're putting in, is that would probably bring annual truck expenditures down on a net basis just somewhere between $200 million and $225 million.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"And then I would add to that the -- whatever investments you're making in self-storage to get an idea what your gross CapEx is?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Rocky Wardrip",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"That's correct.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Okay. Joe, if the firm does\u2026.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"(Operator Instructions) Your next question comes from the line of Ross Haberman.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"How are you?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"I think you might have cut Barrett off, but I am sure he will come back on. Joe, a follow up to his question, what is the cap -- have you said what the capital expenditures are going to be calendar '08 in total?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"No, we haven't. We actually do that calculation based on the fiscal year which is, as you know, March 31 anniversary. So, no, we haven't. Rocky may have, of course, he's constantly projecting it on a rolling basis, but I don't know Rocky.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"What have you spend to date, Rocky, if I may ask?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Rocky Wardrip",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I beg your pardon.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"What have we spent for the nine months, I guess for CapEx?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Rocky Wardrip",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Jason, do you have that number handy. I don't have it on my fingertips.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Including everything we've for the nine months it was $420 million of which truck purchases are the largest portion of that that also includes all other CapEx too which would include storage.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Is that a net or is that a gross number?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"That's a gross number.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Okay. Because this is very confusing and\u2026\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":null,
  "speakertypename":"Analysts",
  "componenttext":"Well, the net would be less to trucks you've sold?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Yeah. Our sales of property, plants and equipment during the period were $134 million.\n"
 },
 {

In [9]:
print(formatted_transcripts[15056])

[
 {
  "transcriptcomponenttypename":"Presentation Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Good morning. My name is Ruth, and I will be your conference Operator today. At this time, I would like to welcome everyone to the AMERCO second quarter fiscal 2009 investor conference call. All lines have been placed on mute to prevent any background noise. After the speakers\u2019 remarks, there will be a question-and-answer session. (Operator Instructions). Ms. Flachman, Director of Investor Relations, you may begin your conference.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Jennifer Flachman",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Thank you for joining us today, and welcome to the AMERCO second quarter fiscal 2009 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995, and certain factors could cause actual results to differ materially from those projected.\nFor a brief discussion of the risks and uncertainties that may affect AMERCO\u2019s business and future operating results, please refer to Form 10-Q for the quarter ended September 30, 2008, which is on file with the Securities and Exchange Commission.\nParticipating in the call today will be Joe Shoen, Chairman of AMERCO. I will now turn the call over to Joe.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning. I am speaking to you from Phoenix, Arizona, and I am joined here by Jason Berg, our Chief Accounting Officer; and Gary Horton, our Chief of Finance; Rocky Wardrip, our Assistant Treasurer is participating via phone from Reno. They will all be available to answer questions. I am going to have Jason start by walking through the numbers and we will go straight into the question and answer. Jason?\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning. Yesterday, we reported second quarter earnings of $2.10 per share compared to $2.39 for the same period in fiscal 2008. Rental[2:03] revenues for the quarter increased $3.5 million. For the quarter and for the first six months of this fiscal year we have been operating with fewer trucks than last year at this time.\nFor the quarter, our truck count was down about 3.5% compared with the same period last year, and for the six months we were down about 4%. As Joe mentioned in our last quarterly call, we have had issues with one of our suppliers fulfilling their product delivery commitment to us for small box truck. This shortage continued into the second quarter. We estimate the loss revenues due to this shortfall to be in the $6 - 7 million range for the last six months.\nDespite this comparative decrease in inventory, we were able to increase total truck rental transactions for the second quarter of fiscal 2009 as compared to the same period last year. We did this through improvements in utilization. Increased truck and trailer transactions drove the U-Move revenue increase for the quarter. \nCompetitor rates continue to have a negative influence on our revenues. While our revenue per transaction statistics over the last two quarters indicate a softening trend and price decline. Competitive rate pressures still way on our result. Our competitors\u2019 actions combined with the current economic stress affecting our customers could dampen our revenues in the near term.\nDuring the quarter, we added over 5600 new box trucks to the fleet and replaced approximately 1200 pick ups and cargo vans. For the first six months of fiscal 2009, we have invested approximately $375 million in new rental equipment, compared to approximately $390 million last year during the same six month period. We have increased our finance allocation to operating leases this year, funding approximately $242 million compared to $130 million last year at this time. \nIn our GAAP cash flow statement, we net, operating leases funding against equipment purchases. Our current plans for the last six months of this year include investing approximately $140 million in new rental equipment. \nOur initial projection assumed used equipment sales in the neighborhood of $150 million to $160 million for the full year. This projection may fall short based upon the current price trends of the used truck market. Continuing now with the used truck market, our loss from the disposal of rental equipment has increased $6.4 million during the second quarter of fiscal 2009 compared with the same period last year. This increase is nearly $12 million for the first six months of this year. I cannot accurately project what these losses will look like over the last six month of this fiscal year, we will continue to see this negative year-over-year fluctuation continue.\nRevenues for our storage program decreased 1.3% for the second quarter of fiscal 2009, as compared to the same period last year. Our occupancy rates are down 4.7% to 81.8 for the quarter. This variance is arrived at for two factors. First, we have fewer rooms rented this year than last year. Our average number of rooms occupied has decreased 2.2% for the quarter. Second, our average number of available rooms has increased almost 3.5% compared to the same quarter last year.\nOur recorded occupancy statistics consider all available storage rooms. We do not adjust for same store comparison. We have had some new projects come online over the last 12 months that are on the ramp up phase. These have added new rooms faster than we can rent them leading to some dilution of our occupancy rates.\nEarnings from operations for the second quarter of fiscal 2009 were $95.5 million compared to $109.1 million for the same period last year. The most significant drivers of these decreases are depreciation and equipment lease expense and the loss from the disposal of equipment.\nNet cash provided by operating activities for the first six months of fiscal 2009 were $245.4 million compared with $279.7 million for the same period last year. Last year, included nearly $40 million of repayments received unrelated party assets primarily from stock holdings. Excluding these non-recurrent payments, operating cash flows at the Moving and Storage segment, for the first six months of this year were essentially flat year-over-year and down approximately 5% for the second quarter.\nCash and short term investments, excluding the insurance companies were $345.8 million at September 30, 2008 with additional cash availability from existing borrowing facilities of $67.7 million. AMERCO notes and loans payable were $1.575 billion at September 30, 2008. Regarding our rental equipment operating leases, using the average cost of our fleet-related debt as the discount rate, the present value of our minimum lease payments and residual value guarantees were $625.3 million at September 30, 2008.\nWith that, I would like to hand the call back over to Joe.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Thanks very much, Jason. We will go to question and answers now.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"(Operator Instructions). Your first question comes from the line of Ross Haberman. Your line is open.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"In the quarter, did you end up settling up with your supplier on the trucks or does it continue to be a shortfall going into this next quarter as well, or I guess there was a strike and you were caught short in terms of truck supplies; has that all been settled and caught up by now?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Yes, it is. It has caught backup now. So, the loss that we have is history. It will roll forward, but it should not accrete[8:25] and so, I think that is the question you are trying to find out.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"Right.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Are we going to see more of that? No, I do not believe so.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"And just one, what do you see on pricing for the storage business? I just know personally what I am seeing at least in the Northeast that prices are coming down. It seems like at least from what I have seen in the Northeast here. Are you seeing that phenomena nationwide?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"We run a standard promotion, which is a 30-day free move-in for a one-way truck or trailer customer. That is our standard promotion, and pricing is always a combination of discounts and the real price. We do not do another price promotional. We do not do pay six get one free. There are a lot of different variations out there. Our public storage, for instance, has a very standard $1 move-in, so it is the same as our 30-day free, just another way to give the discount. I do not see discounts up, and we have not yet lowered prices at more than one or two stores, if at one or two. I cannot recall one. We are very, I do not know what to say, obstinate on that. So, I am not seeing prices decline. Obviously, this is a very geographically specific business and whenever somebody is in your exact geographic area. It is very common for a guy to get the idea, look, if I drop my price, I will get all the business. So, I would expect to see some of that, especially given all the product that came on board in the last three or four years. I think we should just expect to see it.\nMy experience is if you get right down to it that will not get them the rooms. Now, if they stay consistently 30% below you, sure you are going to have to make some adjustments. So far we have not seen that drastically affecting our consumer behavior, although in specific cases, it is present even when some prices were going up. We had a competitor built literally across the street, and to lure business they would rent all the rooms at 50% off or something. It is destructive. We actively encourage people in the self storage business to maintain prices obviously, and we were not about to be the one who has the reputation for dumping price as well.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"Just one question, does JPMorgan have a big storage operation, and are they more competitive than any of the other ones?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Ross, this is Gary. Would you repeat the question?\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"Does JPMorgan Bank have a division that owns storage businesses, and are they more competitive that any body else?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I did not know they had such a division, so I apologize. Now, there may be a JPMorgan person on the line, and if they know, I would appreciate them speaking up. Could you give me any more color on that?\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"No, I just happened to see that just personally I have got some space out on Long Island, and it was supposedly bought by a division of JPMorgan.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Well, you have got me.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"I did not mean to stump you.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"With all the different pieces of JPMorgan out of the private equity side and so on and so forth, it could be possible. But I have not heard of any\u2026\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Anybody who has got into a storage property in the last four years will be suicidal if they drop prices.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"No, I mean I am just seeing and here is what I was getting at, I am seeing advertisements at least locally in the Northeast, basically lowering monthly prices, giving the first half off on the first three or four months. Things like that and that is why I asked the question.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Those who had been out there, they may be just advertising them harder. But this idea of, if you will do a multi-month contract, we will give you some kind of a discount. It is always boiling. Now, I do not know any of the majors doing that.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"Okay.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"But again, that is done all the time and I would not just get panicked. I would turn off.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"No, I am just wondering if that is a trend that you are beginning to see more and more. Given what seems to be a temporary overcapacity.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I would say no, but after your question, I will go do some digging.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ross Haberman",
  "companyofperson":"Haberman Fund",
  "speakertypename":"Analysts",
  "componenttext":"Okay, thank you.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Your next question comes from the line of Jim Barrett. Your line is open.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Joe, did you mention pricing in the self move truck sector? You did not mention it was weak or soft, is it getting worse or is it just remaining as difficult as it has been for the past year or so?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I think we could argue it is better than it was a year, a year and a half ago. It still is, Jim, that people who are struggling to do business will go five or 10 back if you respirate[14:24]. They will ask you a question like, are you a member AARP or a member of AAA or are you a packer fan? That was the best one I have ever been asked. And if so, we have a discount today. Well, if that gets fought out at the individual location level, and of course, the problem is my people will match most of those too, so, if you say that somebody gave you an AARP discount or a AAA discount or a military discount, my person will attempt to chime in and match the incentives. So, there has not been a lot of creativity in pricing. We have stabilized some pricing just because with the pricing programming we put in two years ago, we have been able to get incredibly more specific, and so we keep finding a little pocket we can, that we were either underpriced or for one reason or another we can get another 5% or 7% out of, and so we are able to balance it. But if you talk say, let us say, we were talking the Boston\/New York corridor or DC\/Atlanta corridor, I do not think those are any different than they were a year ago.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"I see. And can you talk generally about the Company\u2019s competitive position in self move truck at this juncture? Do you feel better about it when you look down the road, the same, worse?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Well, I would not want to be the other guy, let me put it that way, okay. Not that I do not have my opportunities. We are relatively well positioned. Our fleet is in terrific condition. We are always unhappy with our distribution, but that is our job to be unhappy about. We could still use a few more small trucks, but we are adding them, and we are trying to probe demand without oversupplying it. Everybody is faced with this declining truck price, and it is impacting us. But it has got to be less than the other guy, because the other guy\u2019s truck is going out at $10,000 to $15,000, which means it needs to be financed, Jim.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Right.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Edward Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"So, ours, as you know, our average truck is going out around $3500, which means it is a cash transaction. There is not a lot of financing out there.\n"
 },
 {

In [10]:
# search_matches = capiq.find_text('very much trying to function as a price leader')
# search_matches

In [13]:
x = capiq.get_transcripts([9063])

Loading library list...
Done
WRDS connection established.

In [14]:
x[9063]

'[\n {\n  "transcriptcomponenttypename":"Presentation Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Good morning. My name is Andrea, and I will be your conference operator today. At this time, I would like to welcome everyone to the AMERCO third quarter fiscal 2008 investor conference call. (Operator Instructions)\\nThank you. Ms. Flachman, you may begin your conference.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Thank you for joining us today, and welcome to the AMERCO third quarter fiscal 2008 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995. Certain factors could cause actual results to differ materially from those projected. For a brief discussion of the risks and uncertainties that may affect AMERCO\'s business and future operating results, please refer to Form 10-Q for the quarter ended December 31, 2007, which is on file with the Securities and Exchange Commission.\\nParticipating in the call today will be Joe Shoen, AMERCO\'s Chairman. I will now turn the call over to Mr. Shoen.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning. This is Joe Shoen. I am speaking you to you from Phoenix, Arizona. Rocky Wardrip, our Assistant treasurer and Jason Berg our Chief Accounting Officer are on the call with me today and they will both be available for questions.\\nU-Haul continued to experience a tough revenue and transaction environment in the just finished third quarter. At the same time, we continued to reap the expense line benefits of the heavy investments we\'ve made in truck replacements over the past 30 months. The primary cost reduction was in repair and maintenance expense on trucks that are no longer in our rental fleet, another word is retired vehicles.\\nWe will continue to aggressively bring in new truck replacements through at least the next two quarters. Our new rental truck weight making system we introduced late last spring has starting to show some results. It allows us to manage with more precision in many small markets we serve and U-Haul\'s distinguished from it\'s compared in that we are in many small markets.\\nWe continue to show rate leadership where we can do so without adversely effecting market share. I intend for us to continue to do this, however, overall rates remain depressed. As I mentioned repair and maintenance was a bright spot in the quarter and it was largely result of decisions made a year or more ago. At the point of sales, my current efforts are focused on improving the rental experience of our exiting customer base. Working on the fundamentals of blocking and tackling in our business will clearly deliver improved results over the long-term.\\nI\'m watching the macro environment in terms of fuel issues and sustainability issues. I don\'t believe they are presently impacting on results but I think they are capable of doing so. My intent is to have U-Haul positioned a little bit ahead of problem should they arise.\\nOverall U-Haul equipment rentals will likely be very tight in the fourth quarter. As I have indicated before, U-Haul is vulnerable to bad winter weather as this late in the year of loss of gross revenue flows disproportionately to the bottomline. On the other hand, our U-Haul self-storage product did not have this same issue and is more predictable. On the insurance company front, both the insurance companies continue to deliver results at planned levels. You should expect them to continue to do so over the near term.\\nWe\'ll now go to the question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, we\'re ready for question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Andrea, this is Joe at U-Haul. We would like to go to question-and-answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"At this time, sir, your first question comes from Ian Gilson.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Well, how are you, Ian?\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good results. Very good results. I do have a question regarding the operating segment\'s results and I know that SAC Holding revenue dropped from $10.8 million to $3.55 million and the earnings from operations dropped to $3.01 to $0.85 million. Did they sell properties or what happened here?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Hi, Ian. This is Jason. During the quarter SAC Holding II was deconsolidated from our financial statements. SAC Holding II\'s parent company, Blackwater, made a contribution to SAC Holding II, that triggered a reevaluation of its consolidated status with us. We made that evaluation and based upon our accounting analysis of the facts and circumstances, they were deconsolidated effective October 31st. So, the results shown in the financial statements you\'re looking for a fiscal 2008, the third quarter includes only one month of activity for SAC Holding II. In future periods, we will not be consolidating any new activity from SAC Holding II.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I would add to that that I consider this a blessing. The last four years we\'ve been stuck in an accounting convention that caused us to consolidate certain of the income and expenses of that company, although that didn\'t reflect any of the actual economic benefit either way. Going ahead, you\'ll see the SAC relationship in management fee income and interest income and that will be more predictable, and it also indicates true economic affect.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. So there is an impact on the overall income statement, but it\'s like a minority ownership.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, not exactly. We won\'t be showing any of their future income. Now we still have to consolidate their activity through October 31st, so you are going to see those numbers remain in the financial statements as long as those historical periods are shown, but going forward any new activity will not be consolidated.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"You have no financial interest in SAC II?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No. We no longer consolidate SAC II. But we still have junior notes with them, interest income and we also manage their storage properties for them. We will receive management fees from them, which will show up in the U-Haul financial statements as management fee income.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Which is precisely what the economic relationship has been, but the accounting presentation has been subject to certain accounting conventions that aren\'t always get on with the economic relations should be. And now these two are going to be mere each other more closely. Including them in our gross revenue is confusing, but including them in our interest income which we do get actual interest income managed with fee income and of course, to the extent they are U-Haul dealers or they do U-Haul revenue, of course, we see all that revenue. So there is still a lot of flows, but the flows are presented on an income statement basis, which is really where the economic interest is.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Since you do get the benefit of the U-Haul dealer on the storage side, is SAC II growing, stable, declining? Can you give us an idea of what that U-Haul revenue streamline look like?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"The U-Haul revenue stream that we receive from the management fee...\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, no he means the truck\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Yeah. The truck rental from the sites that are in the SAC II and other SAC properties.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They very much mere the entire company. So I can\'t give you, I don\'t have it in my command their actual quarter results. They are going to be very much -- mirror the whole company. So in other words they were flat for the quarter or maybe up a tiny of a percent or something. There is no prospect of them diminishing, Ian, but I would expect them to grow at or below the companies overall because SAC is not adding the locations in the -- going ahead as we add a location. The intent is to add it at the U-Haul level and not at the SAC level. So you would see hopefully more growth at the U-Haul level.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Great. Thanks very much.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Your next question comes from the line of Jim Barrett.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning, everyone.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, Jim.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Joe, you talk about that in a couple of quarters as you see the above average investment in trucks are coming down, can you give us any sense as to what the - first of all, what the might represent?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"If I said that, I misspoke a little bit. For the next two quarters, I expect to continue to be aggressive which is above what you\'ve seen going on, okay. I think we\'re -- Jason you might correct me, we have something like 7,000 to 10,000 trucks we\'re committed to right now and that\'s a strong replacement, I am hedging my bid as to what all do mid-summer, another words going into the second quarter of the New Year, which should be more than 180 days from now because we\'re kind of getting somewhere is near the tipping point where we\'ve done enough replacement and if were not going to see increased revenue which we haven\'t seen as you know, Jim, over the last 16 months -- if we\'re not going to see increased revenue than we shouldn\'t increase the truck fleet.\\nI wish I could, it may sound very crude to you that this could be a 5,000 or 7,000 truck window but that\'s really about as precise as it can be. Somewhere in there, where I think we\'ve replaced trucks that we needed to do aggressively and we would go into a more normal cycle, which very likely would be this August or September. And that would be a reduction, a guess at that, Jim would be to take and put it at 10,000 trucks annually.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"On a going forward basis is that sort of beyond this summer that would be sort of a broad run rate?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think that would be with the exception that if we saw some big market opportunity but there has been no big market opportunity we\'ve identified over the last 16 months. So I mean, I am the eternal optimist, I am always looking forward, but we\'re not going to spend money based on optimism. We\'re going to have a definite plan and see something that we can pro forma out over a period of years.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"If it comes to that, Joe, doesn\'t that mean your capital expenditures do come down markedly?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"They come down -- I would defer to Rocky as to exactly how that trickles through the whole financial statement because it\'s never is direct but ordinarily my experience is when those come down you pick up a little bit of an income. Rocky, you might comment on that.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Yeah. And my guess, Jim, and depending on the mix what you\'re putting in, is that would probably bring annual truck expenditures down on a net basis just somewhere between $200 million and $225 million.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"And then I would add to that the -- whatever investments you\'re making in self-storage to get an idea what your gross CapEx is?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s correct.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Joe, if the firm does\\u2026.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"(Operator Instructions) Your next question comes from the line of Ross Haberman.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"How are you?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"I think you might have cut Barrett off, but I am sure he will come back on. Joe, a follow up to his question, what is the cap -- have you said what the capital expenditures are going to be calendar \'08 in total?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"No, we haven\'t. We actually do that calculation based on the fiscal year which is, as you know, March 31 anniversary. So, no, we haven\'t. Rocky may have, of course, he\'s constantly projecting it on a rolling basis, but I don\'t know Rocky.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have you spend to date, Rocky, if I may ask?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I beg your pardon.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ross Haberman",\n  "companyofperson":null,\n  "speakertypename":"Analysts",\n  "componenttext":"What have we spent for the nine months, I guess for CapEx?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Rocky Wardrip",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jason, do you have that number handy. I don\'t have it on my fingertips.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Including everything we\'ve for the nine months it was $420 million of which truck purchases are the largest portion of that that also includes all other CapEx too which would include storage.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Is that a net or is that a gross number?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That\'s a gross number.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Okay. Because this is very confusing and\\u2026\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonnam

In [12]:
capiq.disconnect()

WRDS connection closed.