In [1]:
import modules.capiq as capiq

In [2]:
capiq.connect()

Loading library list...
Done
WRDS connection established.

In [3]:
# Component type table
capiq.ciqtranscriptcomponenttype()

   transcriptcomponenttypeid           transcriptcomponenttypename
0                          1         Presentation Operator Message
1                          2                      Presenter Speech
2                          3                              Question
3                          4                                Answer
4                          5                  Presentation Section
5                          6           Question And Answer Section
6                          7  Question and Answer Operator Message
7                          8   Unknown Question and Answer Message

In [4]:
# Download transcripts
transcript_df, person_df = capiq.dl_transcripts([11154, 15056])

In [5]:
transcript_df

,transcriptcomponentid,transcriptid,componentorder,transcriptcomponenttypeid,transcriptpersonid,componenttext
31,791545,11154,1,1,1,Good morning. My name is Brandy and I will be ...
65,791546,11154,2,2,50718,"Thank you for joining us today, and welcome to..."
100,791547,11154,3,2,50733,"Good morning, everybody. I am speaking to you ..."
8,791548,11154,4,7,1,(Operator Instructions). Your first question c...
32,791549,11154,5,3,9596,"Good morning, everyone.\n"
...,...,...,...,...,...,...
145,1081138,15056,97,4,57496,"Under leasing, it is a very interesting becaus..."
175,1081139,15056,98,3,51252,Okay. Gary thanks.\n
200,1081140,15056,99,7,1,"Mr. Shoen, if you would like to make any closi..."
225,1081141,15056,100,4,74946,"Well, thank you all very much for your support..."
146,1081142,15056,101,7,1,This concludes today’s conference call. You ma...

In [6]:
person_df

,transcriptcomponentid,transcriptid,transcriptpersonname,companyofperson,speakertypename
0,791545.0,11154.0,Operator,None,Operator
1,791546.0,11154.0,Jennifer Flachman,None,Executives
2,791547.0,11154.0,Joe Shoen,None,Executives
3,791548.0,11154.0,Operator,None,Operator
4,791549.0,11154.0,Jim Barrett,CL King & Associates,Analysts
...,...,...,...,...,...
221,1081138.0,15056.0,Gary Horton,None,Executives
222,1081139.0,15056.0,Ian Gilson,Zacks Investments,Analysts
223,1081140.0,15056.0,Operator,None,Operator
224,1081141.0,15056.0,Edward Shoen,None,Executives
225,1081142.0,15056.0,Operator,None,Operator

In [7]:
formatted_transcripts = capiq.format_transcript(transcript_df, person_df)
formatted_transcripts

{np.int64(11154): '[\n {\n  "transcriptcomponenttypename":"Presentation Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Good morning. My name is Brandy and I will be your conference operator today. At this time I would like to welcome everyone to the AMERCO first quarter fiscal 2009 investor call. (Operator Instructions). Thank you. Ms. Flachman, you may begin your conference.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Thank you for joining us today, and welcome to the first quarter fiscal 2009 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995, and certain factors could cause actual results to differ materially from those projected.\\nFor a brief discussion of the risks and uncertainties that may affect AMERCO\'s business and future operating results, please refer to Form 10-Q for the quarter ended June 30, 2008, which is on file with the Securities and Exchange Commission.\\nParticipating in the call today will be Joe Shoen, AMERCO\'s Chairman and CEO. I will now turn the call over to Joe.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, everybody. I am speaking to you from Phoenix, Arizona. I have Gary Horton and Jason Berg in the room with me. Rocky Wardrip joins us from Reno. Of course, we will all be available to respond to your questions after my remarks.\\nFour things I would like to comment on. First, we have decreased a plan on ten-foot truck availability due to the American Axle strike. Second, an improvement in utilization of our moving trucks. The overall flatness in U-Move revenue and softness in resale prices of trucks that are exiting our fleet.\\nWe had talked about the American Axle strike when we last spoke. We incorrectly believed that when that strike resolved itself, GM would begin production per prior plan. In fact, once the strike resolved itself, GM went into a very halting production, in fact, slowed production by our measure, and so we have been doubly put off now by the consequence of the American Axle strike.\\nIt is anybody\'s guess, but we are going to be down for the year at least $4 million to $7 million because of this. It could be worse. We still do not have all the trucks. So, I do not have hard numbers, but we are losing the summer with these trucks, basically. As you all can imagine that is our best revenue period.\\nSecond point is utilization. I think that is the brightest news here. As you know, we do not publish utilization figure. However, we are up, and we are up solidly. We, this quarter, the way that they count the fleet, we were down an average in excess of 4000 units over the same time last year.\\nSo in order to keep revenue where we kept it, we actually got better utilization. We did not get huge price increases. As Jim Barrett commented in his write-up, it is a little bit difficult to project a price increase or a decrease, but I think it would be best for practical purposes to say prices stayed fairly constant, yet we were able to get revenue up, which means utilization went up basically.\\nSo that is very positive. That is the fundamental economics of the business. It means a lot of people did something right. However, the overall result, as I indicated is, revenue was flat to down in the U-Move segment, and I do not think there is a prospect of it being greatly different in the second quarter, but the same basic factors are all operating, and I will be, actually, extremely thrilled if we can keep utilization where we have been running it, and I do not know that we can, because we are running at an all-time high on utilization, which is hard to project out that you are going to hold that, but we are working to do that.\\nThe final point is one I think that I did not give you any a heads-up on, and I think to some extent caught me a little bit unawares through the first quarter. That is softness in truck resale prices, which softness we saw across all models.\\nWe have all heard the auto makers are struggling at the auto auctions, and that is just a truism. I under-appreciated the affect it would have. We saw it throughout the quarter and it is continuing in the second quarter.\\nGains on pickups and vans which we have typically made a gain on sale have been substantially eroded. Box trucks for the quarter, essentially, sold for a little less than what their residual values were, so we posted a loss. From your purposes, this, I believe all blends into the depreciation line, so it is a little bit of a black hole from your point of view. I wanted to give you a little window into it, because we continue to sell about 8,000 pickups and vans a year, and about 9,000 to 9,500 box trucks a year.\\nSo it is a substantial effort on our side, and the result there, which has been fairly predictable for a long time, slipped in the first quarter and likely will slip in the second quarter.\\nI am continuing to focus daily on our U-Move transactions and revenue. Anytime I keep hammering on something, and I have now been hammering on this for 18 months, it causes some loss of focus in other parts of our business. That is, how many balls can I get the team to juggle?\\nSo I think you are seeing a little bit of that in retail sales and self-storage. I will continue to attempt to balance our activities to get the best result over the long term for all parties concerned.\\nOur fleet remains very well positioned which I think is a positive. We are relatively well-financed, which I see as a big positive. Customer satisfaction, which is, there is no real good index of it or hard index of it.\\nThe customer satisfaction appears to be improving not declining. Typically, when we increase utilization, which means we are very tight scheduling equipment, customer satisfaction drops because some people get left out in the lurch, because things did not work out as we had planned.\\nSo, I see that as a big thing that utilization went up, but it does not appear that customers are more dissatisfied than they were at this time last year. So I think that is very positive.\\nOverall, our business remains very solid but tight. With that, I am going to turn the call over to the moderator for questions and answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"(Operator Instructions). Your first question comes from Jim Barrett with CL King & Associates.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning, everyone.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, Jim.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Joe, this is an accounting question. Your use of accelerated depreciation; can you give us any thought as to at what point does that catch up with straight-line depreciation? In other words, at what point does it stop penalizing your GAAP earnings?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jim, hi. This is Jason. We start to reach that point at about year five on that. I would also like to point out that we have changed our allocation this year of how we are funding new fleet acquisitions. We have gone more towards operating leases versus fleet loans. So we are going to see the lease expense number begin to go up, which goes up at a slower rate than if we were to buy the equipment and depreciate it. So there may be a moderation of the depreciation expense over the course of this year as compared to the increases that you have seen in that line in the last two years.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I see. Year five break even, what fiscal year would you estimate that to be?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Well, we started this depreciation method in the third quarter of fiscal \'06. We have really been adding quite a few trucks. If you were to compare with what it would have been under straight line, I do not have that specific date. However, we are still quite a few years out from that just because of how much we have put on.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jason, I am going to butt in here, at the risk of destroying it totally. I should not normally comment on accounting. I think that there is two places where these become equal. One is where accumulated depreciation in the fleet becomes the same under both methods, and the other is where annual depreciation crosses over. I think Jim is looking, I think, Jim, at the point when annual depreciation crosses over.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That is correct.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think Jason answered, when accumulated depreciation crosses over. I believe annual depreciation is going to cross over in the third year.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I see.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I am doing this from memory, Jim, but I am very much interested in the subject. So my memory is not totally bad. Because, I believe Jason what actually happens is, the last two years you have less depreciation than you would under a lease; and the first two and almost three years you have substantially more.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jim, I need to actually revise my comment.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Alright.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Under the declining balance method, in the first year we are taking 16% off the value of the truck. Under the straight line that would have been a little over 5%. So under the declining method it goes 16, 13, 11, 9, 8, 7 and 6. So we are actually out to about year seven or eight before the annual depreciation number would be equivalent to what it would be under the straight line. So the accumulated piece would actually be even further out than that, because the accumulated piece is not going to reach until that straight line eclipses the declining balance.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I understand that. Joe on a separate subject, there was a mention in the Q that the company has additional opportunities for leverage in its existing capital structure. Would you care to comment on where those additional opportunities are, and what their magnitude might be?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I am going to let Gary Horton speak to it; he is here.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Could you rephrase that again?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"He wants to know where do we have room for more leverage here in our capital structure.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"We probably have some more room on our real estate assets. We have basically; I think a few, two quarters ago, we basically terminated a loan that we had on our used truck fleet. We still have a tremendous amount of value in the older fleet that we could leverage up. We could probably leverage, like I said in a little bit more of our real estate.\\nWe have basically have gone through and with the reluctance of the credit providers in the market to look at real estate. That will probably go for another year or so. Then we will go ahead and put some leverage on that as we go forward. I think we have some operational leverage also.\\nWhat Joe was talking a little bit about by bringing the utilization up from where it had been, and I think, part of it is coming out of our new pricing model, which is allowing us to be much more aggressive on certain pricing and certain moves. So I think those are the two areas where you can look in the leverage.\\nI would also like to just say that when you look at the front of the Q, in looking at depreciation, and you see it going from $44 million to $64 million, a big portion of that, Jim, is caused by what we have done with taking the gain or loss into that line as a reduction. Last year, we actually had a sale of a property in New York, which had the effect of reducing the line, and this year, as Joe had pointed out, we also had more losses on the sale of our trucks. So that was a pretty big swing right there.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Last but not least, Gary, speaking of real estate, since you last had the real estate, I assume appraised by the banks, and the last time the company borrowed against that real estate, broadly speaking, has the value of your properties gone up, down or sideways?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think I am going to say primarily sideways. In certain markets, they actually have the effect of increasing in value. We do not have and none of our loans are tied primarily to loan to value, so we do not have that risk. We really have structured all of those to be based upon cash flows and debt service coverage. So we are very strong there.\\nWe do not get caught with the whipsaw, where a lot of the people have done that, and the loan to value is too high, and oh my God. Then people start doing fire sales and other things. We do not have those problems going forward. As Joe said, we are very well capitalized. Our maturities are very manageable going forward. Again, a lot of that is done in timing, and we put out all the real estate from multi years.\\nI think we have one loan next year that comes up at an actual maturity, and it is somewhere around $40 million.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Thank you, all.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Your next question comes from Ian Gilson wick Zacks Investments.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":"Zacks Investments",\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning. Joe, you are talking about increasing the leverage; that means basically you would have extra cash. What are you going to use it for?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Right now we are keeping it for a rainy day Ian. However, we are like everybody else, if the opportunity of the decade comes up, we would be foolish not to jump on it. I have not seen any fire sales either in the self-storage business, or in the equipment business. However, I do not see every deal out there, and I have high hopes if something came up, particularly in the self-storage business, that we would have sufficient liquidity to act on it, if it was anywhere near proportional to something we have business doing.\\nSo, right now we are basically saving it for a rainy day. You have been around a long time. This current economic doldrums or whatever you want to call it could last a year. It could last four years. Nobody owns that piece of information that I am aware of. So we are taking a fairly conservative posture.\\nYet I will not lie to you. I am average greedy, and if something that looked pretty exciting came up, I would try to get us to step up. So having some liquidity would be key, because it seems that there is at least for us, liquidity is not easy to come by right now. In other words, the lenders are not out there just trying to shower money on everybody who has a proposition. So if something came up, having some of our own liquidity, I think we will have a better chance to actually close a deal.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"You know, Ian, where we came from and what we went through. We want to make sure that we do have a conservative amount of liquidity. As we look at it, we have got a substantial amount of cash and liquidity at this point.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"For our standards. Where is a lot for us historically?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Yes, it is $300 million plus.\\n"\n },\n {\n  "transcriptcompone

In [8]:
formatted_transcripts = capiq.get_transcripts([11154, 15056])
formatted_transcripts

{np.int64(11154): '[\n {\n  "transcriptcomponenttypename":"Presentation Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Good morning. My name is Brandy and I will be your conference operator today. At this time I would like to welcome everyone to the AMERCO first quarter fiscal 2009 investor call. (Operator Instructions). Thank you. Ms. Flachman, you may begin your conference.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Jennifer Flachman",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Thank you for joining us today, and welcome to the first quarter fiscal 2009 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995, and certain factors could cause actual results to differ materially from those projected.\\nFor a brief discussion of the risks and uncertainties that may affect AMERCO\'s business and future operating results, please refer to Form 10-Q for the quarter ended June 30, 2008, which is on file with the Securities and Exchange Commission.\\nParticipating in the call today will be Joe Shoen, AMERCO\'s Chairman and CEO. I will now turn the call over to Joe.\\n"\n },\n {\n  "transcriptcomponenttypename":"Presenter Speech",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, everybody. I am speaking to you from Phoenix, Arizona. I have Gary Horton and Jason Berg in the room with me. Rocky Wardrip joins us from Reno. Of course, we will all be available to respond to your questions after my remarks.\\nFour things I would like to comment on. First, we have decreased a plan on ten-foot truck availability due to the American Axle strike. Second, an improvement in utilization of our moving trucks. The overall flatness in U-Move revenue and softness in resale prices of trucks that are exiting our fleet.\\nWe had talked about the American Axle strike when we last spoke. We incorrectly believed that when that strike resolved itself, GM would begin production per prior plan. In fact, once the strike resolved itself, GM went into a very halting production, in fact, slowed production by our measure, and so we have been doubly put off now by the consequence of the American Axle strike.\\nIt is anybody\'s guess, but we are going to be down for the year at least $4 million to $7 million because of this. It could be worse. We still do not have all the trucks. So, I do not have hard numbers, but we are losing the summer with these trucks, basically. As you all can imagine that is our best revenue period.\\nSecond point is utilization. I think that is the brightest news here. As you know, we do not publish utilization figure. However, we are up, and we are up solidly. We, this quarter, the way that they count the fleet, we were down an average in excess of 4000 units over the same time last year.\\nSo in order to keep revenue where we kept it, we actually got better utilization. We did not get huge price increases. As Jim Barrett commented in his write-up, it is a little bit difficult to project a price increase or a decrease, but I think it would be best for practical purposes to say prices stayed fairly constant, yet we were able to get revenue up, which means utilization went up basically.\\nSo that is very positive. That is the fundamental economics of the business. It means a lot of people did something right. However, the overall result, as I indicated is, revenue was flat to down in the U-Move segment, and I do not think there is a prospect of it being greatly different in the second quarter, but the same basic factors are all operating, and I will be, actually, extremely thrilled if we can keep utilization where we have been running it, and I do not know that we can, because we are running at an all-time high on utilization, which is hard to project out that you are going to hold that, but we are working to do that.\\nThe final point is one I think that I did not give you any a heads-up on, and I think to some extent caught me a little bit unawares through the first quarter. That is softness in truck resale prices, which softness we saw across all models.\\nWe have all heard the auto makers are struggling at the auto auctions, and that is just a truism. I under-appreciated the affect it would have. We saw it throughout the quarter and it is continuing in the second quarter.\\nGains on pickups and vans which we have typically made a gain on sale have been substantially eroded. Box trucks for the quarter, essentially, sold for a little less than what their residual values were, so we posted a loss. From your purposes, this, I believe all blends into the depreciation line, so it is a little bit of a black hole from your point of view. I wanted to give you a little window into it, because we continue to sell about 8,000 pickups and vans a year, and about 9,000 to 9,500 box trucks a year.\\nSo it is a substantial effort on our side, and the result there, which has been fairly predictable for a long time, slipped in the first quarter and likely will slip in the second quarter.\\nI am continuing to focus daily on our U-Move transactions and revenue. Anytime I keep hammering on something, and I have now been hammering on this for 18 months, it causes some loss of focus in other parts of our business. That is, how many balls can I get the team to juggle?\\nSo I think you are seeing a little bit of that in retail sales and self-storage. I will continue to attempt to balance our activities to get the best result over the long term for all parties concerned.\\nOur fleet remains very well positioned which I think is a positive. We are relatively well-financed, which I see as a big positive. Customer satisfaction, which is, there is no real good index of it or hard index of it.\\nThe customer satisfaction appears to be improving not declining. Typically, when we increase utilization, which means we are very tight scheduling equipment, customer satisfaction drops because some people get left out in the lurch, because things did not work out as we had planned.\\nSo, I see that as a big thing that utilization went up, but it does not appear that customers are more dissatisfied than they were at this time last year. So I think that is very positive.\\nOverall, our business remains very solid but tight. With that, I am going to turn the call over to the moderator for questions and answers.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"(Operator Instructions). Your first question comes from Jim Barrett with CL King & Associates.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning, everyone.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Good morning, Jim.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Joe, this is an accounting question. Your use of accelerated depreciation; can you give us any thought as to at what point does that catch up with straight-line depreciation? In other words, at what point does it stop penalizing your GAAP earnings?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jim, hi. This is Jason. We start to reach that point at about year five on that. I would also like to point out that we have changed our allocation this year of how we are funding new fleet acquisitions. We have gone more towards operating leases versus fleet loans. So we are going to see the lease expense number begin to go up, which goes up at a slower rate than if we were to buy the equipment and depreciate it. So there may be a moderation of the depreciation expense over the course of this year as compared to the increases that you have seen in that line in the last two years.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I see. Year five break even, what fiscal year would you estimate that to be?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Well, we started this depreciation method in the third quarter of fiscal \'06. We have really been adding quite a few trucks. If you were to compare with what it would have been under straight line, I do not have that specific date. However, we are still quite a few years out from that just because of how much we have put on.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jason, I am going to butt in here, at the risk of destroying it totally. I should not normally comment on accounting. I think that there is two places where these become equal. One is where accumulated depreciation in the fleet becomes the same under both methods, and the other is where annual depreciation crosses over. I think Jim is looking, I think, Jim, at the point when annual depreciation crosses over.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"That is correct.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think Jason answered, when accumulated depreciation crosses over. I believe annual depreciation is going to cross over in the third year.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I see.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I am doing this from memory, Jim, but I am very much interested in the subject. So my memory is not totally bad. Because, I believe Jason what actually happens is, the last two years you have less depreciation than you would under a lease; and the first two and almost three years you have substantially more.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Jim, I need to actually revise my comment.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Alright.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Under the declining balance method, in the first year we are taking 16% off the value of the truck. Under the straight line that would have been a little over 5%. So under the declining method it goes 16, 13, 11, 9, 8, 7 and 6. So we are actually out to about year seven or eight before the annual depreciation number would be equivalent to what it would be under the straight line. So the accumulated piece would actually be even further out than that, because the accumulated piece is not going to reach until that straight line eclipses the declining balance.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"I understand that. Joe on a separate subject, there was a mention in the Q that the company has additional opportunities for leverage in its existing capital structure. Would you care to comment on where those additional opportunities are, and what their magnitude might be?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I am going to let Gary Horton speak to it; he is here.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Could you rephrase that again?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"He wants to know where do we have room for more leverage here in our capital structure.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"We probably have some more room on our real estate assets. We have basically; I think a few, two quarters ago, we basically terminated a loan that we had on our used truck fleet. We still have a tremendous amount of value in the older fleet that we could leverage up. We could probably leverage, like I said in a little bit more of our real estate.\\nWe have basically have gone through and with the reluctance of the credit providers in the market to look at real estate. That will probably go for another year or so. Then we will go ahead and put some leverage on that as we go forward. I think we have some operational leverage also.\\nWhat Joe was talking a little bit about by bringing the utilization up from where it had been, and I think, part of it is coming out of our new pricing model, which is allowing us to be much more aggressive on certain pricing and certain moves. So I think those are the two areas where you can look in the leverage.\\nI would also like to just say that when you look at the front of the Q, in looking at depreciation, and you see it going from $44 million to $64 million, a big portion of that, Jim, is caused by what we have done with taking the gain or loss into that line as a reduction. Last year, we actually had a sale of a property in New York, which had the effect of reducing the line, and this year, as Joe had pointed out, we also had more losses on the sale of our trucks. So that was a pretty big swing right there.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Okay. Last but not least, Gary, speaking of real estate, since you last had the real estate, I assume appraised by the banks, and the last time the company borrowed against that real estate, broadly speaking, has the value of your properties gone up, down or sideways?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Gary Horton",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"I think I am going to say primarily sideways. In certain markets, they actually have the effect of increasing in value. We do not have and none of our loans are tied primarily to loan to value, so we do not have that risk. We really have structured all of those to be based upon cash flows and debt service coverage. So we are very strong there.\\nWe do not get caught with the whipsaw, where a lot of the people have done that, and the loan to value is too high, and oh my God. Then people start doing fire sales and other things. We do not have those problems going forward. As Joe said, we are very well capitalized. Our maturities are very manageable going forward. Again, a lot of that is done in timing, and we put out all the real estate from multi years.\\nI think we have one loan next year that comes up at an actual maturity, and it is somewhere around $40 million.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Jim Barrett",\n  "companyofperson":"CL King & Associates",\n  "speakertypename":"Analysts",\n  "componenttext":"Thank you, all.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question and Answer Operator Message",\n  "transcriptpersonname":"Operator",\n  "companyofperson":null,\n  "speakertypename":"Operator",\n  "componenttext":"Your next question comes from Ian Gilson wick Zacks Investments.\\n"\n },\n {\n  "transcriptcomponenttypename":"Question",\n  "transcriptpersonname":"Ian Gilson",\n  "companyofperson":"Zacks Investments",\n  "speakertypename":"Analysts",\n  "componenttext":"Good morning. Joe, you are talking about increasing the leverage; that means basically you would have extra cash. What are you going to use it for?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Right now we are keeping it for a rainy day Ian. However, we are like everybody else, if the opportunity of the decade comes up, we would be foolish not to jump on it. I have not seen any fire sales either in the self-storage business, or in the equipment business. However, I do not see every deal out there, and I have high hopes if something came up, particularly in the self-storage business, that we would have sufficient liquidity to act on it, if it was anywhere near proportional to something we have business doing.\\nSo, right now we are basically saving it for a rainy day. You have been around a long time. This current economic doldrums or whatever you want to call it could last a year. It could last four years. Nobody owns that piece of information that I am aware of. So we are taking a fairly conservative posture.\\nYet I will not lie to you. I am average greedy, and if something that looked pretty exciting came up, I would try to get us to step up. So having some liquidity would be key, because it seems that there is at least for us, liquidity is not easy to come by right now. In other words, the lenders are not out there just trying to shower money on everybody who has a proposition. So if something came up, having some of our own liquidity, I think we will have a better chance to actually close a deal.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"You know, Ian, where we came from and what we went through. We want to make sure that we do have a conservative amount of liquidity. As we look at it, we have got a substantial amount of cash and liquidity at this point.\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Joe Shoen",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"For our standards. Where is a lot for us historically?\\n"\n },\n {\n  "transcriptcomponenttypename":"Answer",\n  "transcriptpersonname":"Jason Berg",\n  "companyofperson":null,\n  "speakertypename":"Executives",\n  "componenttext":"Yes, it is $300 million plus.\\n"\n },\n {\n  "transcriptcompone

In [10]:
print(formatted_transcripts[11154])

[
 {
  "transcriptcomponenttypename":"Presentation Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Good morning. My name is Brandy and I will be your conference operator today. At this time I would like to welcome everyone to the AMERCO first quarter fiscal 2009 investor call. (Operator Instructions). Thank you. Ms. Flachman, you may begin your conference.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Jennifer Flachman",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Thank you for joining us today, and welcome to the first quarter fiscal 2009 investor call. Before we begin, I would like to remind everyone that certain of the statements during this call regarding general revenues, income and general growth of our business, constitute forward-looking statements contemplated under the Private Securities Litigation Reform Act of 1995, and certain factors could cause actual results to differ materially from those projected.\nFor a brief discussion of the risks and uncertainties that may affect AMERCO's business and future operating results, please refer to Form 10-Q for the quarter ended June 30, 2008, which is on file with the Securities and Exchange Commission.\nParticipating in the call today will be Joe Shoen, AMERCO's Chairman and CEO. I will now turn the call over to Joe.\n"
 },
 {
  "transcriptcomponenttypename":"Presenter Speech",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning, everybody. I am speaking to you from Phoenix, Arizona. I have Gary Horton and Jason Berg in the room with me. Rocky Wardrip joins us from Reno. Of course, we will all be available to respond to your questions after my remarks.\nFour things I would like to comment on. First, we have decreased a plan on ten-foot truck availability due to the American Axle strike. Second, an improvement in utilization of our moving trucks. The overall flatness in U-Move revenue and softness in resale prices of trucks that are exiting our fleet.\nWe had talked about the American Axle strike when we last spoke. We incorrectly believed that when that strike resolved itself, GM would begin production per prior plan. In fact, once the strike resolved itself, GM went into a very halting production, in fact, slowed production by our measure, and so we have been doubly put off now by the consequence of the American Axle strike.\nIt is anybody's guess, but we are going to be down for the year at least $4 million to $7 million because of this. It could be worse. We still do not have all the trucks. So, I do not have hard numbers, but we are losing the summer with these trucks, basically. As you all can imagine that is our best revenue period.\nSecond point is utilization. I think that is the brightest news here. As you know, we do not publish utilization figure. However, we are up, and we are up solidly. We, this quarter, the way that they count the fleet, we were down an average in excess of 4000 units over the same time last year.\nSo in order to keep revenue where we kept it, we actually got better utilization. We did not get huge price increases. As Jim Barrett commented in his write-up, it is a little bit difficult to project a price increase or a decrease, but I think it would be best for practical purposes to say prices stayed fairly constant, yet we were able to get revenue up, which means utilization went up basically.\nSo that is very positive. That is the fundamental economics of the business. It means a lot of people did something right. However, the overall result, as I indicated is, revenue was flat to down in the U-Move segment, and I do not think there is a prospect of it being greatly different in the second quarter, but the same basic factors are all operating, and I will be, actually, extremely thrilled if we can keep utilization where we have been running it, and I do not know that we can, because we are running at an all-time high on utilization, which is hard to project out that you are going to hold that, but we are working to do that.\nThe final point is one I think that I did not give you any a heads-up on, and I think to some extent caught me a little bit unawares through the first quarter. That is softness in truck resale prices, which softness we saw across all models.\nWe have all heard the auto makers are struggling at the auto auctions, and that is just a truism. I under-appreciated the affect it would have. We saw it throughout the quarter and it is continuing in the second quarter.\nGains on pickups and vans which we have typically made a gain on sale have been substantially eroded. Box trucks for the quarter, essentially, sold for a little less than what their residual values were, so we posted a loss. From your purposes, this, I believe all blends into the depreciation line, so it is a little bit of a black hole from your point of view. I wanted to give you a little window into it, because we continue to sell about 8,000 pickups and vans a year, and about 9,000 to 9,500 box trucks a year.\nSo it is a substantial effort on our side, and the result there, which has been fairly predictable for a long time, slipped in the first quarter and likely will slip in the second quarter.\nI am continuing to focus daily on our U-Move transactions and revenue. Anytime I keep hammering on something, and I have now been hammering on this for 18 months, it causes some loss of focus in other parts of our business. That is, how many balls can I get the team to juggle?\nSo I think you are seeing a little bit of that in retail sales and self-storage. I will continue to attempt to balance our activities to get the best result over the long term for all parties concerned.\nOur fleet remains very well positioned which I think is a positive. We are relatively well-financed, which I see as a big positive. Customer satisfaction, which is, there is no real good index of it or hard index of it.\nThe customer satisfaction appears to be improving not declining. Typically, when we increase utilization, which means we are very tight scheduling equipment, customer satisfaction drops because some people get left out in the lurch, because things did not work out as we had planned.\nSo, I see that as a big thing that utilization went up, but it does not appear that customers are more dissatisfied than they were at this time last year. So I think that is very positive.\nOverall, our business remains very solid but tight. With that, I am going to turn the call over to the moderator for questions and answers.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"(Operator Instructions). Your first question comes from Jim Barrett with CL King & Associates.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Good morning, everyone.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Good morning, Jim.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Joe, this is an accounting question. Your use of accelerated depreciation; can you give us any thought as to at what point does that catch up with straight-line depreciation? In other words, at what point does it stop penalizing your GAAP earnings?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Jim, hi. This is Jason. We start to reach that point at about year five on that. I would also like to point out that we have changed our allocation this year of how we are funding new fleet acquisitions. We have gone more towards operating leases versus fleet loans. So we are going to see the lease expense number begin to go up, which goes up at a slower rate than if we were to buy the equipment and depreciate it. So there may be a moderation of the depreciation expense over the course of this year as compared to the increases that you have seen in that line in the last two years.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"I see. Year five break even, what fiscal year would you estimate that to be?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Well, we started this depreciation method in the third quarter of fiscal '06. We have really been adding quite a few trucks. If you were to compare with what it would have been under straight line, I do not have that specific date. However, we are still quite a few years out from that just because of how much we have put on.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Jason, I am going to butt in here, at the risk of destroying it totally. I should not normally comment on accounting. I think that there is two places where these become equal. One is where accumulated depreciation in the fleet becomes the same under both methods, and the other is where annual depreciation crosses over. I think Jim is looking, I think, Jim, at the point when annual depreciation crosses over.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"That is correct.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I think Jason answered, when accumulated depreciation crosses over. I believe annual depreciation is going to cross over in the third year.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"I see.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I am doing this from memory, Jim, but I am very much interested in the subject. So my memory is not totally bad. Because, I believe Jason what actually happens is, the last two years you have less depreciation than you would under a lease; and the first two and almost three years you have substantially more.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Jim, I need to actually revise my comment.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Alright.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Under the declining balance method, in the first year we are taking 16% off the value of the truck. Under the straight line that would have been a little over 5%. So under the declining method it goes 16, 13, 11, 9, 8, 7 and 6. So we are actually out to about year seven or eight before the annual depreciation number would be equivalent to what it would be under the straight line. So the accumulated piece would actually be even further out than that, because the accumulated piece is not going to reach until that straight line eclipses the declining balance.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"I understand that. Joe on a separate subject, there was a mention in the Q that the company has additional opportunities for leverage in its existing capital structure. Would you care to comment on where those additional opportunities are, and what their magnitude might be?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I am going to let Gary Horton speak to it; he is here.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Could you rephrase that again?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"He wants to know where do we have room for more leverage here in our capital structure.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"We probably have some more room on our real estate assets. We have basically; I think a few, two quarters ago, we basically terminated a loan that we had on our used truck fleet. We still have a tremendous amount of value in the older fleet that we could leverage up. We could probably leverage, like I said in a little bit more of our real estate.\nWe have basically have gone through and with the reluctance of the credit providers in the market to look at real estate. That will probably go for another year or so. Then we will go ahead and put some leverage on that as we go forward. I think we have some operational leverage also.\nWhat Joe was talking a little bit about by bringing the utilization up from where it had been, and I think, part of it is coming out of our new pricing model, which is allowing us to be much more aggressive on certain pricing and certain moves. So I think those are the two areas where you can look in the leverage.\nI would also like to just say that when you look at the front of the Q, in looking at depreciation, and you see it going from $44 million to $64 million, a big portion of that, Jim, is caused by what we have done with taking the gain or loss into that line as a reduction. Last year, we actually had a sale of a property in New York, which had the effect of reducing the line, and this year, as Joe had pointed out, we also had more losses on the sale of our trucks. So that was a pretty big swing right there.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Okay. Last but not least, Gary, speaking of real estate, since you last had the real estate, I assume appraised by the banks, and the last time the company borrowed against that real estate, broadly speaking, has the value of your properties gone up, down or sideways?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Gary Horton",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"I think I am going to say primarily sideways. In certain markets, they actually have the effect of increasing in value. We do not have and none of our loans are tied primarily to loan to value, so we do not have that risk. We really have structured all of those to be based upon cash flows and debt service coverage. So we are very strong there.\nWe do not get caught with the whipsaw, where a lot of the people have done that, and the loan to value is too high, and oh my God. Then people start doing fire sales and other things. We do not have those problems going forward. As Joe said, we are very well capitalized. Our maturities are very manageable going forward. Again, a lot of that is done in timing, and we put out all the real estate from multi years.\nI think we have one loan next year that comes up at an actual maturity, and it is somewhere around $40 million.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Jim Barrett",
  "companyofperson":"CL King & Associates",
  "speakertypename":"Analysts",
  "componenttext":"Thank you, all.\n"
 },
 {
  "transcriptcomponenttypename":"Question and Answer Operator Message",
  "transcriptpersonname":"Operator",
  "companyofperson":null,
  "speakertypename":"Operator",
  "componenttext":"Your next question comes from Ian Gilson wick Zacks Investments.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":"Zacks Investments",
  "speakertypename":"Analysts",
  "componenttext":"Good morning. Joe, you are talking about increasing the leverage; that means basically you would have extra cash. What are you going to use it for?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Right now we are keeping it for a rainy day Ian. However, we are like everybody else, if the opportunity of the decade comes up, we would be foolish not to jump on it. I have not seen any fire sales either in the self-storage business, or in the equipment business. However, I do not see every deal out there, and I have high hopes if something came up, particularly in the self-storage business, that we would have sufficient liquidity to act on it, if it was anywhere near proportional to something we have business doing.\nSo, right now we are basically saving it for a rainy day. You have been around a long time. This current economic doldrums or whatever you want to call it could last a year. It could last four years. Nobody owns that piece of information that I am aware of. So we are taking a fairly conservative posture.\nYet I will not lie to you. I am average greedy, and if something that looked pretty exciting came up, I would try to get us to step up. So having some liquidity would be key, because it seems that there is at least for us, liquidity is not easy to come by right now. In other words, the lenders are not out there just trying to shower money on everybody who has a proposition. So if something came up, having some of our own liquidity, I think we will have a better chance to actually close a deal.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"You know, Ian, where we came from and what we went through. We want to make sure that we do have a conservative amount of liquidity. As we look at it, we have got a substantial amount of cash and liquidity at this point.\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Joe Shoen",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"For our standards. Where is a lot for us historically?\n"
 },
 {
  "transcriptcomponenttypename":"Answer",
  "transcriptpersonname":"Jason Berg",
  "companyofperson":null,
  "speakertypename":"Executives",
  "componenttext":"Yes, it is $300 million plus.\n"
 },
 {
  "transcriptcomponenttypename":"Question",
  "transcriptpersonname":"Ian Gilson",
  "companyofperson":"Zacks Investments",
  "speakertypename":"Analysts",

In [9]:
capiq.disconnect()

WRDS connection closed.